---

- hosts: all
  become: true
  tasks:
  
  - name: install apache2 and php package
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
