---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"

  - name: install php
    yum:
      name: php
      state: latest
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
