---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    yum:
      update_cache: yes

  - name: remove apache2 and php package
    yum:
      name:
        - httpd
        - php
      state: absent
