---

- hosts: all
  become: true
  pre_tasks:

  - name: install update
    yum:
      update_only: yes
      update_cache: yes

- hosts: web_server
  become: true
  tasks:
  
  - name: install apache2 and php package
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"

- hosts: db_server
  become: true
  tasks:

  - name: isntall mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"
